In [1]:
import os
import numpy as np

In [19]:
path = "/mnt/disk1/backup_user/dang.nh4/ecg_instruct/ecg"
x = []

for folder in os.listdir(path):
    imgs_path = os.path.join(path, folder)
    x.extend(os.listdir(imgs_path))

In [20]:
len(x)

24455

In [ ]:
cd LLaVA
# python llava/eval/run_llava.py --model-path "PULSE-ECG/PULSE-7B" --image-file "images/ecg_example.png" --query "What are the main features in this ECG image?" --conv-mode "llava_v1"

In [7]:
import sys
sys.path.append("/home/dang.nh4/PULSE/LLaVA")

from llava.model.builder import load_pretrained_model
from llava.mm_utils import (
    get_model_name_from_path,
)
from llava.model import LlavaQwen2ForCausalLM

In [4]:
import sys
sys.path.append("/home/dang.nh4/PULSE/")
from llava.model import *
import torch

model = LlavaQwen2ForCausalLM.from_pretrained(
    "apple/FastVLM-1.5B",
    cache_dir=None,
    attn_implementation=None,
    torch_dtype=torch.bfloat16
)

/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[2025-12-20 16:31:48,591] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)


/home/dang.nh4/miniconda3/envs/ecg-qa/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/torch/utils/cpp_extension.py:28: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import packaging  # type: ignore[attr-defined]
/home/dang.nh4/miniconda3/envs/ecg-qa/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  war

In [5]:
model = LlavaQwen2ForCausalLM.from_pretrained(
    "/home/dang.nh4/PULSE/test/dangngu",
    cache_dir=None,
    attn_implementation=None,
    torch_dtype=torch.bfloat16
)

In [3]:
model.save_pretrained("./dangngu")

In [4]:
model.load_state_dict("/home/dang.nh4/PULSE/test/dangngu")

TypeError: Expected state_dict to be dict-like, got <class 'str'>.

In [19]:
for n, _ in model.named_parameters():
    if "project" in n:
        print(n)

model.mm_projector.0.weight
model.mm_projector.0.bias
model.mm_projector.2.weight
model.mm_projector.2.bias


In [ ]:
torch.save(model.model.mm_projector.state_dict(), "./")

In [11]:
model_path="PULSE-ECG/PULSE-7B"
model_name = get_model_name_from_path(model_path)
model = load_pretrained_model(
    model_path,
    None,
    model_name,
)

/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.embeddings.class_embedding: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages

In [10]:
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    low_cpu_mem_usage=True,
)

/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [18]:
import json
import os

imgs_path = "/mnt/disk1/backup_user/dang.nh4/ecg_instruct/ecg/"
path = "/mnt/disk1/backup_user/dang.nh4/ecg_instruct/ECGInstruct.json"
with open(path, 'r') as f:
    data = json.load(f)

small_data = []

for item in data:
    if os.path.exists(os.path.join(imgs_path, item['image'])):
        small_data.append(item)

In [20]:
with open("/mnt/disk1/backup_user/dang.nh4/ecg_instruct/ECGInstruct_small.json", 'w') as f:
    json.dump(small_data, f)

In [1]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "apple/FastVLM-1.5B",
    cache_dir=None,
    model_max_length=512,
    padding_side="right",
    use_fast=False,
)

/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/torch/cuda/__init__.py:51: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated

In [2]:
projector_path = "/home/dang.nh4/PULSE/output/fastvlm1.5B/checkpoint-98876/mm_projector.pth"
import torch
x = torch.load(projector_path)

/home/dang.nh4/miniconda3/envs/ecg-qa/lib/python3.11/site-packages/torch/cuda/__init__.py:51: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [3]:
x

{'base_model.model.model.mm_projector.0.weight': Parameter containing:
 tensor([[ 0.0081,  0.0055, -0.0216,  ..., -0.0118, -0.0072, -0.0222],
         [ 0.0063,  0.0044, -0.0151,  ..., -0.0024,  0.0095,  0.0229],
         [ 0.0006,  0.0055, -0.0188,  ..., -0.0020, -0.0090,  0.0315],
         ...,
         [ 0.0061,  0.0073, -0.0090,  ...,  0.0115, -0.0069,  0.0031],
         [ 0.0061, -0.0143,  0.0197,  ..., -0.0095,  0.0095, -0.0126],
         [-0.0029, -0.0153,  0.0019,  ..., -0.0449, -0.0031, -0.0148]],
        device='cuda:0', dtype=torch.bfloat16, requires_grad=True),
 'base_model.model.model.mm_projector.0.bias': Parameter containing:
 tensor([-0.0022,  0.0093, -0.0226,  ..., -0.0153,  0.0023,  0.0125],
        device='cuda:0', dtype=torch.bfloat16, requires_grad=True),
 'base_model.model.model.mm_projector.2.weight': Parameter containing:
 tensor([[-0.0038, -0.0132,  0.0186,  ...,  0.0199, -0.0041,  0.0287],
         [-0.0150, -0.0123,  0.0227,  ..., -0.0171,  0.0156, -0.0078],
